apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: kafka-streams
build:
  artifacts:
    - image: busybox
      context: streams
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
        env:
            - "GOOGLE_RUNTIME_VERSION=17"
deploy:
  helm:
    releases:
      - name: streams-helm
        chartPath: streams-helm
        valuesFiles:
          - streams-helm/values.yaml
        version: 0.1.0
