replicaCount: 1

image:
  repository: fzampa/streams
  tag: "v0.0.1"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hostname: streams.mylocal
